### PR TITLE
Add black and flake8

### PR DESCRIPTION
**Pull request by killthekitten**
@HunterMcGushion if the changes look overwhelming, consider this is an invitation to discuss.

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
Thanks for tackling the formatting checks! Hahaha I knew lots of changes would be coming. I was planning on going with a Black/Flake8 configuration that I use for my other repos, and I'd love to hear your thoughts on this setup: [Black configuration](https://github.com/HunterMcGushion/hyperparameter_hunter/blob/master/pyproject.toml), [Black/Flake8 execution](https://github.com/HunterMcGushion/hyperparameter_hunter/blob/master/.travis.yml#L35-L40). I imagine the Travis snippet should fit into GitHub Actions with relative ease, but if you disagree with any of these configurations or the implementation, I'm certainly open to discussion. 

Thanks again for single-handedly building the safety net! You're awesome!

**Comment by killthekitten** [comment]
@HunterMcGushion keeping it the same makes sense of course, but it might be confusing to contributors. My thinking here was to stick to defaults as much as possible. It goes along well with the idea behind black :) 

I would change the max line length to 127 and add a black check, but keep the rest as is.

In `hyperparameter_hunter` the 100 chars line length for black seems arbitrary and inconsistent with flake. I like the rationale behind 127 characters though.

Also, I prefer using `setup.cfg` over custom CLI arguments in ci.yml. This way running i.e. `flake8` locally would produce the same result as on CI.

**Comment by HunterMcGushion** [comment]
@killthekitten, that makes sense! I chose 100 as a middle ground between the Python-recommended 79 (which I think is way too short) and 127. However, you make a good point about arbitrary max line lengths being confusing to contributors, so 127 works for me. 

Agreed on adding the Black check and moving the Flake8 CLI arguments and ignored error codes to a config file. Ignoring E266 is of particular importance to me, since I like making header comments to separate blocks of code, as you may have noticed hahaha

**Comment by killthekitten** [comment]
@HunterMcGushion sounds good, I'll update the PR accordingly 👍 

One note on E266 - it's a good indicator that you want to refactor this particular piece of code into a function and use a docstring instead.

**Comment by HunterMcGushion** [comment]
@killthekitten, I'm very sorry, but I just remembered that 127 characters makes reading diffs on GitHub awkward on your average 27-inch (68-cm) monitor. Similarly, at 127 characters it is no longer possible to have two split vertical panes in PyCharm (don't know about other IDEs). I apologize if I'm being unreasonable, but what are your thoughts on 100 characters (or some other number) given this limitation?

**Comment by killthekitten** [comment]
@HunterMcGushion I'm good with any limit as long as its consistent 👍

**Comment by HunterMcGushion** [comment]
> I'm good with any limit as long as it's consistent 

Thank you, sir! Sorry about the flip-flopping.

> One note on E266 - it's a good indicator that you want to refactor this particular piece of code into a function and use a docstring instead.

Hahaha that's a good point. I just ran into that in PR #19, and I plan on refactoring other confusing areas into helper functions. All the same, I've still found them helpful in other instances when refactoring code into different functions is undesirable.

**Comment by killthekitten** [comment]
@HunterMcGushion updated the PR, you are welcome to make header comments now (as long as you keep them under 100 characters) 😅 

Also, I've split the dependencies into two separate files (`requirements-lint.txt` and `requirements-test.txt`). This is to not install black in the test step - can't do that for python versions below 3.6.

**Comment by HunterMcGushion** [comment]
@killthekitten, thanks a lot! Regarding the two separate requirements files, how would you feel about using `setup`’s `extras_require` kwarg with a “lint” key? Seems cleaner than having several requirements files, but if you think that’s the way to go, then I can get on board with separate files. 

Also, which linting rule puts the docstring’s starting triple quotes on their own line? I’m assuming it’s Flake8, since Black’s own docstrings don’t put the starting quotes on their own line. Is this an important change to you? If not, I’d prefer to revert back to having the description start on the same line as the triple quotes. That said, I’ve seen it both ways, so I’ll defer to your expertise.

**Comment by killthekitten** [comment]
@HunterMcGushion great point on `extras_require` 👍 

Regarding the multiline docstring, linters are ok both ways. It's my personal preference to start the docstring on the new line. Updated 👍

**Comment by HunterMcGushion** [comment]
This is awesome! Thanks for all your hard work and for putting up with me, @killthekitten!

**Pull request merged**
