### PR TITLE
Add deprecated notes to CLI options

### LINKED ISSUE #37: [RFC] Deprecate CLI options to use kebab-case
If anyone has any thoughts/ideas on this, please feel free to comment (especially if you think this is a bad idea).

I'd like to convert all CLI options to use kebab-case. Specifically, this would affect the following options:
- `--skipmagic` -> `--skip-magic`
- `--skipfiledoc` -> `--skip-file-doc`
- `--skipinit` -> `--skip-init`
- `--skipclassdef` -> `--skip-class-def`
- `--followlinks` -> `--follow-links`
- `--failunder` -> `--fail-under`

We would need a deprecation cycle during which both the old and new names are usable, but a deprecation warning is logged when an old option is used. The problem is that, as far as I can tell, [Click](https://github.com/pallets/click) has no native way to deprecate options -- only entire commands.

Something like [this SO answer](https://stackoverflow.com/a/50402799/8936527) seems promising. However, I have some reservations about monkey-patching another open-source repo. Perhaps we could avoid some problems by pinning our `setup.py` to a specific Click version, but that also doesn't seem ideal. 

I'd appreciate hearing from anyone that has any ideas or opinions on this.

### PR DESCRIPTION
**Pull request by cthoyt**
This PR closes #37 by adding more new CLI options and logic to deal with upgrading the names of the variables

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
This looks way better than what I was thinking. Thanks a lot, @cthoyt!

**Comment by cthoyt** [comment]
@HunterMcGushion this doesn't quite work yet since i'm using none checks. I have another fix in mind!

**Comment by cthoyt** [comment]
@HunterMcGushion not sure what's going on with black, I ran it on py37 like in your workflow and also on py39 and nothing seems to be out of place

**Comment by HunterMcGushion** [comment]
@cthoyt, hmmm that error message isn't very helpful... I'll pull your branch onto my machine and see if I can reproduce it.

**Comment by cthoyt** [comment]
@HunterMcGushion should be good now

**Comment by HunterMcGushion** [comment]
@cthoyt, this is amazing! Do you think we can group all of the deprecated options together at the bottom? The output of `docstr-coverage --help` is a bit confusing with them scattered throughout. What do you think?

**Comment by cthoyt** [comment]
I've got no opinion. Will take care of that now. FYI if you want to make tweaks it's also possible for the owner of a repo to push to branches that have open pull requests :)

**Comment by HunterMcGushion** [comment]
Oh, thank you for teaching me something new!

**Comment by cthoyt** [comment]
Done in 747c7c0

**Comment by HunterMcGushion** [comment]
Thanks a lot, @cthoyt! This is fantastic

**Pull request merged**
