### PR TITLE
Ignore @property, @setter and @deleter

### PR DESCRIPTION
**Pull request by MiWeiss**
As discussed on the roadmap. 

@HunterMcGushion This is now ready for review.

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
This is great, @MiWeiss! I think we should default `--skip-setter` and `--skip-deleter` to True, since the getter is supposed to provide all the documentation. For reference, see [this SO post](https://stackoverflow.com/questions/16025462/what-is-the-right-way-to-put-a-docstring-on-python-property) and [the Python docs](https://docs.python.org/3/library/functions.html#property), particularly the third code block. What do you think?

**Comment by MiWeiss** [comment]
Very good idea. I'll have to see how I change that (given that now it's a flag). What would you prefer?
```
docstr-coverage --include-setters  REPO/PATH
````
or 
````
docstr-coverage --ignore-setters True REPO/PATH
````

**Comment by MiWeiss** [comment]
Btw. I'll probably work on this next week, so feel free to skip this for `v2.1.0`

**Comment by MiWeiss** [comment]
@HunterMcGushion This is now ready for your next pass

**Review by HunterMcGushion — APPROVED** [review]
Awesome additions, @MiWeiss! Thank you!

**Pull request merged**
