### PR TITLE
Deprecate old config file

### PR DESCRIPTION
**Pull request by MiWeiss**
This fulfills the TODO in the code and makes our (documented) CLI a bit slimmer.

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
@MiWeiss, I like the idea of removing the extra `docstr-ignore-file`, but rather than just removing the functionality, I think it would make sense to add the patterns it used as a new option that can be defined in the new config file. 

I think it's useful to allow people to declare regexes of nodes that should be ignored. What are your thoughts?

**Comment by MiWeiss** [comment]
Hi @HunterMcGushion 

Fully agree - and it's already implemented on the main branch :-) Example from README.md:

```yaml
ignore_patterns: # Dict with key/value pairs of file-pattern/node-pattern
  .*: method_to_ignore_in_all_files
  FileWhereWeWantToIgnoreAllSpecialMethods: "__.+__"
  SomeFile:
    - method_to_ignore1
    - method_to_ignore2
    - method_to_ignore3
  a_very_important_view_file:
    - "^get$"
    - "^set$"
    - "^post$"
  detect_.*:
    - "get_val.*"
```

Do you have something additional in mind?

**Comment by HunterMcGushion** [comment]
Hahaha please forgive my forgetfulness. We probably want to keep that documented in the readme, then. Otherwise, we're just using an otherwise unmentioned argument (and a fairly complicated one at that) in the config file example. If I'm overlooking some mention of it elsewhere, then that's fine. We just need to make sure that option is listed and documented

**Comment by MiWeiss** [comment]
@HunterMcGushion This minor change was left aside forgotten and alone for too long ;-) Especially in light of #115 we should probably merge this now.

The PR is now ready for your pass.

**Review by HunterMcGushion — APPROVED** [review]

**Comment by HunterMcGushion** [comment]
Looks great, @MiWeiss! Thank you!

**Pull request merged**
