### PR TITLE
Badges and Banner 

### PR DESCRIPTION
**Pull request by MiWeiss**
Just some colors for the people who happen to end up on our readme ;-)

Tip: You can preview the changes on my fork branch: [https://github.com/MiWeiss/docstr_coverage/tree/readme](https://github.com/MiWeiss/docstr_coverage/tree/readme)

Note: In a future commit (once the banner logo has been merged), we can update the link in the readme to point to the base repository instead of to my fork. I would not yet do this during the review, as typos in the url would go unnoticed (we'd expect the image not to show at all).

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
Hahaha I love it!! I'm excited to change the social preview image to this as well, so it's not just my face all the time!

**Comment by HunterMcGushion** [comment]
Just to be sure, this is ready to merge now, correct? 
Also, the plan is to merge this with the existing link and comment, and then update the image link in a follow-up immediately after, is that right?

**Comment by MiWeiss** [comment]
> Just to be sure, this is ready to merge now, correct?
> Also, the plan is to merge this with the existing link and comment, and then update the image link in a follow-up immediately after, is that right?

yes, if you have no other suggestions ;)

**Review by HunterMcGushion — APPROVED** [review]
Beautiful work!

**Pull request merged**
