### PR TITLE
chore(): added pre-commit hook

### PR DESCRIPTION
**Pull request by bjornconstructors**
This adds support for using `docstr-coverage`  in a repository as a `pre-commit` hook.

### CODE REVIEW

**Comment by MiWeiss** [comment]
Hi @bjornconstructors 

Thanks a lot for your PR - this has been on my list for a while ;-) I'll review and test your PR this weekend at latest, but don't expect any major revisions.

One thing I already noticed is the missing description on the readme. Would you mind adding a small section before *Package in Your Project*, saying that docstr-coverage can be used in pre-commit and provide an example?

**Comment by bjornconstructors** [comment]
@MiWeiss Done, please note that in the README I'm pointing to the the v2.0.2 tag, which obviously does not exist yet. You might want to adapt that to the correct version once this PR is in.

**Comment by HunterMcGushion** [comment]
Thanks a lot, @bjornconstructors! Have you tested to ensure the pre-commit hook respects configurations in `.docstr.yaml`? Unfortunately I have limited experience with pre-commit hooks, so I apologize if the answer is obvious. What do you and @MiWeiss think about adding a quick note to your new README section to say that's the preferred configuration method? 
Thanks again for your awesome work!

**Comment by bjornconstructors** [comment]
@HunterMcGushion Yup, I freelance for Sendcloud, where this is used in production now with a `.docstr.yaml` :)

I updated the README again, hope it's to both your liking.

**Comment by MiWeiss** [comment]
I tested the hook thoroughly and it works fine and picks up configs as expected. Thanks a lot for your PR, @bjornconstructors 

I took the liberty to slightly change the README.md. Feel free if you disagree with any of the changes. Otherwise @HunterMcGushion, this is ready to be merged & released.

**Review by MiWeiss — APPROVED** [review]

**Comment by bjornconstructors** [comment]
@MiWeiss Looks fine, thanks for the improvement!

**Pull request merged**
